### PR TITLE
Fix `BucketBuilder::delay_action` being poorly documented

### LINKED ISSUE #2099: delay_action doc comment fails to mention await_ratelimits
Relevant source file: [`buckets.rs line 472`](https://github.com/serenity-rs/serenity/blob/b5d7973ad47a61a79225ddb4d59d6dbb3faa34f5/src/framework/standard/structures/buckets.rs#L472).

`delay_action` 's doc comment fails to mention that for it to run, you need to set await_ratelimits to a non-zero value. 
On top of that, it doesn't even mention that you need to make a closure that passes a future from a function you intend to run (probably should be rewritten to avoid that). 

It is important that we write our documentation clearly, so issues like this don't arise. An obvious fix for this would be to rewrite the doc comment so that it mentions the weird quirk and optionally has an example showing it in practice.

### PR DESCRIPTION
**Pull request by NinekoTheCat**
fixes #2099 

This pull request adds better documentation of the usage of delay_action by adding an example along with more clear documentation.

### CODE REVIEW

File: src/framework/standard/structures/buckets.rs [hunk 1]
```diff
@@ -469,7 +469,55 @@ impl BucketBuilder {
...
+        .group(&GENERAL_GROUP);
+    
+    let mut client = Client::builder(&token, GatewayIntents::default())
+    .framework(framework)
+    .await?;
+
+    //presumably you'd then start the client
+    ```
+    You can use this to for example send a custom response when someone exceeds the amount of commands they're allowed to make.
+    */
```
Comment (arqunis) [inline src/framework/standard/structures/buckets.rs]: Rust does not use Java-style `/***...***/` documentation. You have to put `///` before each line for the text to count as the documentation for an item (in this case, the `delay_action` function).

**Review by arqunis — CHANGES_REQUESTED** [review]

File: src/framework/standard/structures/buckets.rs (hunk 1 above)
Comment (NinekoTheCat) [reply src/framework/standard/structures/buckets.rs]: Cargo doc didn't find issues with it and my IDE kept freaking out because of it, please elaborate

Comment (NinekoTheCat) [reply src/framework/standard/structures/buckets.rs]: Nevermind rust RFC doesn't like it. Will change

Comment (arqunis) [reply src/framework/standard/structures/buckets.rs]: Oh? It seems `/**` is an alternative form for documentation comments, which I didn't know before. Anyway, this is not the style we use. We do `///` per line. Like so:
```suggestion
    ///  This function is called when a user's command invocation is delayed when:
    ///  1. await_ratelimits is set to a non zero value (the default is 0).
    ///  2. user's message rests comfortably within await_ratelimits (ex. if you set it to 1 then it will only respond once when the delay is first exceeded).
    ///  Example:
    ///  ```rust
    ///  use serenity::framework::standard::macros::{command, group};
    ///  use serenity::framework::standard::{CommandResult, StandardFramework};
    ///  use serenity::model::channel::Message;
    ///  use serenity::prelude::*;
    ///  #[command]
    ///  #[bucket="example_bucket"]
    ///  async fn example_command(ctx: &Context, msg: &Message) -> CommandResult {
    ///      msg.reply(ctx,"Example message, You can only repeat this once every 10 seconds").await?;

    ///      Ok(())
    ///  }
    ///  async fn example_overuse_response(ctx: &Context, msg: &Message) {
    ///      msg.reply(ctx,"I told you that you can't call this command less than every 10 seconds").await?;
    ///  }
    ///  #[group]
    ///  #[commands(example_command)]
    ///  struct General;

    ///  let token = std::env::var("DISCORD_TOKEN")?;

    ///  let framework = StandardFramework::new()
    ///      .configure(|c| c.prefix("~"))
    ///      //we initialise the bucket with the closure
    ///      .bucket("example_bucket", |b|b.delay_action(|msg,ctx| {
    ///          //we return a future for the function we want to run
    ///          Box::pin(example_overuse_response(ctx,msg))
    ///      })
    ///          //we set the delay to 10 seconds
    ///          .delay(10)
    ///          //we override the default behavior so that the function actually gets ran
    ///          .await_ratelimits(1)
    ///      //we await the return of the bucket
    ///      ).await
    ///      .group(&GENERAL_GROUP);
    ///  
    ///  let mut client = Client::builder(&token, GatewayIntents::default())
    ///  .framework(framework)
    ///  .await?;

    ///  //presumably you'd then start the client
    ///  ```
    ///  You can use this to for example send a custom response when someone exceeds the amount of commands they're allowed to make.
```

Comment (NinekoTheCat) [reply src/framework/standard/structures/buckets.rs]: implemented the change

File: src/framework/standard/structures/buckets.rs [hunk 2]
```diff
@@ -469,7 +469,53 @@ impl BucketBuilder {
         self
     }
 
-    /// This function will be called once a user's invocation has been delayed.
+    /// This function is called when a user's command invocation is delayed when:
+    /// 1. await_ratelimits is set to a non zero value (the default is 0).
+    /// 2. user's message rests comfortably within await_ratelimits (ex. if you set it to 1 then it will only respond once when the delay is first exceeded).
+    /// Example:
```
Comment (arqunis) [inline src/framework/standard/structures/buckets.rs]:
```suggestion
    ///
    /// # Examples
    ///
```

File: src/framework/standard/structures/buckets.rs [hunk 3]
```diff
@@ -469,7 +469,53 @@ impl BucketBuilder {
...
+    ///         .await_ratelimits(1)
+    ///     //we await the return of the bucket
+    ///     ).await
+    ///     .group(&GENERAL_GROUP);
+    ///
+    /// let mut client = Client::builder(&token, GatewayIntents::default())
+    /// .framework(framework)
+    /// .await?;
+    ///
+    /// //presumably you'd then start the client
```
Comment (arqunis) [inline src/framework/standard/structures/buckets.rs]:
```suggestion
    /// # async fn run() -> Result<(), Box<dyn std::error::Error>> {
    /// use serenity::framework::standard::macros::{command, group};
    /// use serenity::framework::standard::{CommandResult, StandardFramework};
    /// use serenity::model::channel::Message;
    /// use serenity::prelude::*;
    ///
    /// #[command]
    /// #[bucket = "example_bucket"]
    /// async fn example_command(ctx: &Context, msg: &Message) -> CommandResult {
    ///     msg.reply(ctx, "Example message, You can only repeat this once every 10 seconds").await?;
    ///
    ///     Ok(())
    /// }
    ///
    /// async fn example_overuse_response(ctx: &Context, msg: &Message) {
    ///     msg.reply(ctx, "I told you that you can't call this command less than every 10 seconds!").await?;
    /// }
    ///
    /// #[group]
    /// #[commands(example_command)]
    /// struct General;
    ///
    /// let token = std::env::var("DISCORD_TOKEN")?;
    ///
    /// let framework = StandardFramework::new()
    ///     .configure(|c| c.prefix("~"))
    ///     .bucket("example_bucket", |b| {
    ///         // We initialise the bucket with the function we want to run
    ///         b.delay_action(|msg, ctx| {
    ///             Box::pin(example_overuse_response(ctx,msg))
    ///         })
    ///     })
    ///     .delay(10) // We set the delay to 10 seconds
    ///     .await_ratelimits(1)).await // We override the default behavior so that the function actually gets run
    ///     .group(&GENERAL_GROUP);
    ///
    /// let mut client = Client::builder(&token, GatewayIntents::default())
    /// .framework(framework)
    /// .await?;
    ///
    /// client.start().await?;
    /// #     Ok(())
    /// # }
```

File: src/framework/standard/structures/buckets.rs [hunk 4]
```diff
@@ -469,7 +469,53 @@ impl BucketBuilder {
...
+    /// ```
+    /// You can use this to for example send a custom response when someone exceeds the amount of commands they're allowed to make.
```
Comment (arqunis) [inline src/framework/standard/structures/buckets.rs]:
```suggestion
```

File: src/framework/standard/structures/buckets.rs [hunk 5]
```diff
@@ -469,7 +469,53 @@ impl BucketBuilder {
         self
     }
 
-    /// This function will be called once a user's invocation has been delayed.
+    /// This function is called when a user's command invocation is delayed when:
+    /// 1. await_ratelimits is set to a non zero value (the default is 0).
+    /// 2. user's message rests comfortably within await_ratelimits (ex. if you set it to 1 then it will only respond once when the delay is first exceeded).
```
Comment (arqunis) [inline src/framework/standard/structures/buckets.rs]:
```suggestion
    /// This function is called when a user's command invocation is delayed when:
    /// 1. `await_ratelimits` is set to a non zero value (the default is 0).
    /// 2. user's message rests comfortably within `await_ratelimits` (ex. if you set it to 1 then it will only respond once when the delay is first exceeded).
    ///
    /// You can use this to, for example, send a custom response when someone exceeds the amount of commands they're allowed to make.
```

**Review by arqunis — CHANGES_REQUESTED** [review]

File: src/framework/standard/structures/buckets.rs [hunk 6]
```diff
@@ -469,7 +469,59 @@ impl BucketBuilder {
...
+    /// let framework = StandardFramework::new()
+    ///     .configure(|c| c.prefix("~"))
+    ///     .bucket("example_bucket", |b| {
+    ///         // We initialise the bucket with the function we want to run
+    ///         b.delay_action(|msg, ctx| {
+    ///             Box::pin(example_overuse_response(ctx,msg))
+    ///         })
+    ///     })
+    ///     .delay(10) // We set the delay to 10 seconds
+    ///     .await_ratelimits(1)).await // We override the default behavior so that the function actually gets run
```
Comment (arqunis) [inline src/framework/standard/structures/buckets.rs]:
```suggestion
    ///     .bucket("example_bucket", |b| {
    ///         // We initialise the bucket with the function we want to run
    ///         b.delay_action(|msg, ctx| {
    ///             Box::pin(example_overuse_response(ctx, msg))
    ///         })
    ///         .delay(10) // We set the delay to 10 seconds
    ///         .await_ratelimits(1) // We override the default behavior so that the function actually gets run
    ///     })
    ///     .await
```

**Review by arqunis — CHANGES_REQUESTED** [review]

File: src/framework/standard/structures/buckets.rs [hunk 7]
```diff
@@ -469,7 +469,60 @@ impl BucketBuilder {
...
+    /// #[commands(example_command)]
+    /// struct General;
+    ///
+    /// let token = std::env::var("DISCORD_TOKEN")?;
+    ///
+    /// let framework = StandardFramework::new()
+    ///     .configure(|c| c.prefix("~"))
+    ///     .bucket("example_bucket", |b| {
+    ///         // We initialise the bucket with the function we want to run
+    ///         b.delay_action(|msg, ctx| {
```
Comment (arqunis) [inline src/framework/standard/structures/buckets.rs]:
```suggestion
    ///         b.delay_action(|ctx, msg| {
```

**Review by arqunis — CHANGES_REQUESTED** [review]

File: src/framework/standard/structures/buckets.rs [hunk 8]
```diff
@@ -469,7 +469,60 @@ impl BucketBuilder {
...
+    /// #[command]
+    /// #[bucket = "example_bucket"]
+    /// async fn example_command(ctx: &Context, msg: &Message) -> CommandResult {
+    ///     msg.reply(ctx, "Example message, You can only repeat this once every 10 seconds").await?;
+    ///
+    ///     Ok(())
+    /// }
+    ///
+    /// async fn example_overuse_response(ctx: &Context, msg: &Message) {
+    ///     msg.reply(ctx, "I told you that you can't call this command less than every 10 seconds!").await?;
```
Comment (arqunis) [inline src/framework/standard/structures/buckets.rs]:
```suggestion
    ///     msg.reply(ctx, "I told you that you can't call this command less than every 10 seconds!").await.unwrap();
```

**Review by arqunis — CHANGES_REQUESTED** [review]

**Review by arqunis — APPROVED** [review]
