### PR TITLE
Make select menu values optional to fix deserialization of msg component interactions

### LINKED ISSUE #2062: Message deserialization errors if it has select menu
If I got the details correct: #1986 accommodated for Discord sending the `values` field on components in the wrong place. Discord seems to have fixed the problem now so deserialization fails due to missing `values` field.

This was noticed via get_interaction_response calls failing with a select menu present in the retrieved message https://discord.com/channels/381880193251409931/919310428344029265/999359158635741224

### PR DESCRIPTION
**Pull request by bumblepie**
Fixes #2062

### CODE REVIEW

**Comment by kangalio** [comment]
One person [already had success](https://discord.com/channels/381880193251409931/381912587505500160/1001540546113847346) with this PR

**Review by kangalio — APPROVED** [review]

**Comment by ForeverAnApple** [comment]
+1 on this PR. Thanks so much.

File: src/model/application/component.rs [hunk 1]
```diff
@@ -153,7 +153,7 @@ pub struct SelectMenu {
     #[serde(default)]
     pub options: Vec<SelectMenuOption>,
     /// The result location for modals
-    pub values: Vec<String>,
+    pub values: Option<Vec<String>>,
```
Comment (arqunis) [inline src/model/application/component.rs]: This is good, but would you mind changing the type back to `Vec<String>` and adding `#[serde(default)]`? This change constitutes as breaking, which isn't typically allowed on `current` (in certain cases it is, but here it's more viable to fix it temporarily and then add the real fix on `next`; that is, using an `Option`).
```suggestion
    #[serde(default)]
    pub values: Vec<String>,
```

**Review by arqunis — CHANGES_REQUESTED** [review]

**Review by arqunis — APPROVED** [review]
