### PR TITLE
Remove Channel::Category

### LINKED ISSUE #1352: Cache and HTTP use different types for channel categories
When you request channel data about a channel category via its channel ID, serenity yields a different object depending on whether it uses HTTP or the cache. HTTP yields a `Channel::Category` and the cache yields a `Channel::Guild` with the `kind` field set to `Category`.

Both of these options kind of make sense but it would be ideal if one was decided upon. Having two separate representations of channel categories makes them harder to handle correctly ([example](https://discord.com/channels/381880193251409931/381912587505500160/844965959273545788)).

I was able to reproduce the problem with
```rust
// Replace with the ID of any channel category of a server your bot is on
let channel = ChannelId(736186039571316827);
dbg!(channel.to_channel(&ctx).await.unwrap()); // HTTP
dbg!(channel.to_channel(&ctx).await.unwrap()); // cache
```
([full code](https://pastebin.com/5vG1RGyJ))

### PR DESCRIPTION
**Pull request by kangalio**
Fixes #1352

Channel categories had two different representations: Channel::Guild(c) with c.kind == ChannelType::Category, and Channel::Category(c). Different parts of serenity used either of these two. This PR unifies serenity to the former.

(I chose the first representation because it results in a lot shorter code, less duplication, is closer to Discord's API, is consistent with how other channel types don't have their own Channel enum variant, makes Channel enum variants be just Guild and Private which is a clean and obvious differentiation.)

### CODE REVIEW

**Comment by kangalio** [comment]
Presumably also fixes #1513

File: src/cache/event.rs [hunk 1]
```diff
@@ -223,21 +186,12 @@ impl CacheUpdate for GuildDeleteEvent {
...
-                            // Remove the channel's cached messages.
-                            cache.messages.remove(channel_id);
-                        },
-                        Channel::Category(_) => {
-                            // Remove the category from the cache
-                            cache.categories.remove(channel_id);
-                        },
-                        _ => {},
-                    }
+                for (channel_id, _) in &guild.1.channels {
```
Comment (arqunis) [inline src/cache/event.rs]: Could you fix the clippy warning here?

File: src/model/guild/member.rs [hunk 2]
```diff
@@ -196,7 +196,7 @@ impl Member {
         let member = guild.members.get(&self.user.id)?;
 
         for channel in guild.channels.values() {
-            if let Channel::Guild(channel) = channel {
+            if channel.kind != ChannelType::Category {
```
Comment (arqunis) [inline src/model/guild/member.rs]: Ditto.

**Review by arqunis — CHANGES_REQUESTED** [review]

**Review by arqunis — APPROVED** [review]
