### PR TITLE
Fix webhook creation on news channel

### LINKED ISSUE #1328: Creating webhooks on annoucement channels fails
Here's a transcript of the discussion from #development

### PR DESCRIPTION
**Pull request by Zaitara**
This PR fixes the webhook creation on news channel, and also add the methods to `ChannelId`.

This has been tested.

Closes #1328

### CODE REVIEW

File: src/model/channel/guild_channel.rs [hunk 1]
```diff
@@ -111,6 +108,15 @@ pub struct GuildChannel {
 
 #[cfg(feature = "model")]
 impl GuildChannel {
+    /// Whether or not this channel is text-based, meaning that
+    /// it is possible to send messages.
+    pub fn is_text_based(&self) -> bool {
+        match self.kind {
+            ChannelType::Text | ChannelType::News => true,
+            _ => false,
+        }
```
Comment (arqunis) [inline src/model/channel/guild_channel.rs]:
```suggestion
        matches!(self.kind, ChannelType::Text | ChannelType::News)
```

**Review by arqunis — CHANGES_REQUESTED** [review]

**Review by arqunis — APPROVED** [review]
