### PR TITLE
Change Arc<Mutex<ShardManager>> to Arc<ShardManager>

### LINKED ISSUE #2507: Shutdown is broken on `next` branch
Since the revert of #2400 in #2486, it is impossible to shutdown a serenity bot without killing the process. Calling `ShardManager.shutdown_all()` will hang forever and results in the following warning being logged:
```
WARN shutdown_all:shutdown{shard_id=ShardId(0) code=1000}: serenity::gateway::bridge::shard_manager: 287: Failed to cleanly shutdown shard 0, reached timeout: Elapsed(())
```

### PR DESCRIPTION
**Pull request by tazz4843**
Has the side effect of (theoretically)
fixing shutdown by removing the major deadlock

Required converting all `&mut self` methods on ShardManager to &self

Closes #2507

### CODE REVIEW

**Comment by tazz4843** [comment]
Accidentally opened as ready for merge, converted to draft as I don't want a round 2 of last time we tried fixing shutdown. I'm going to fire up a local bot as a test and leave it running for a few days.

File: src/gateway/bridge/shard_manager.rs [hunk 1]
```diff
@@ -96,20 +97,25 @@ use crate::model::gateway::GatewayIntents;
...
     /// The shard runners currently managed.
     ///
     /// **Note**: It is highly unrecommended to mutate this yourself unless you need to. Instead
     /// prefer to use methods on this struct that are provided where possible.
     pub runners: Arc<Mutex<HashMap<ShardId, ShardRunnerInfo>>>,
     /// The index of the first shard to initialize, 0-indexed.
-    shard_index: u32,
+    ///
+    /// Atomic integers are used here that way we don't need any mutable references to Self to
+    /// update any of these values.
```
Comment (mkrasnitski) [inline src/gateway/bridge/shard_manager.rs]:
```suggestion
    // Atomics are used here to allow for mutation without requiring a mutable reference to self.
```
This should be made a regular comment IMO.

File: src/gateway/bridge/shard_manager.rs [hunk 2]
```diff
@@ -96,20 +97,25 @@ use crate::model::gateway::GatewayIntents;
...
+    shard_index: AtomicU32,
     /// The number of shards to initialize.
-    shard_init: u32,
+    shard_init: AtomicU32,
     /// The total shards in use, 1-indexed.
-    shard_total: u32,
+    shard_total: AtomicU32,
     shard_queuer: Sender<ShardQueuerMessage>,
-    shard_shutdown: Receiver<ShardId>,
+    // we can safely use a Mutex for this field, as it is only ever used in one single place
```
Comment (mkrasnitski) [inline src/gateway/bridge/shard_manager.rs]:
```suggestion
    // We can safely use a Mutex for this field, as it is only ever used in one single place
```
Nit

**Review by mkrasnitski — COMMENTED** [review]
Looks good to me - let's hope this works. Your doctests are failing, though.

**Comment by tazz4843** [comment]
Turns out this breaks poise as well, I'll make a PR to that as a companion.

File: src/gateway/bridge/shard_manager.rs (hunk 1 above)
Comment (tazz4843) [reply src/gateway/bridge/shard_manager.rs]: I thought I did that, might've accidentally copied and pasted. Thanks!

**Comment by GnomedDev** [comment]
Is this a good idea? Have you tested running shutdown concurrently to see if that breaks anything? It worries me if this was written with the assumption that it's `&mut self` that a new class of bugs will be introduced (that cannot be caught by rustc, as we are mutating the state of the program via IO to discord).

**Comment by mkrasnitski** [comment]
The only fields of `ShardManager` that end up being mutated are `shard_shutdown` as well as the integers `shard_index`, `shard_init`, and `shard_total`. The former is now behind a Mutex that only gets locked in one place, so no opportunity for deadlocks on the same thread.

The other three fields all get written to only in `.set_shards`. There *could* feasibly be a race condition where a context switch happens between two of the calls to `.store`, and then an invariant of the manager might get broken? I don't know. Maybe we should synchronize the three atomic writes to make sure they can't get interrupted.

**Comment by tazz4843** [comment]
> Have you tested running shutdown concurrently to see if that breaks anything?

As far as I can tell, `shutdown` is a completely idempotent function, even with these new changes. The worst that could happen is an extra irrelevant "timed out" warning after a successful shutdown, which would have happened previously anyways. `shutdown` simply fires a message and then waits for a response, and if it doesn't get it, times out with an error.

> The other three fields all get written to only in `.set_shards`. There _could_ feasibly be a race condition where a context switch happens between two of the calls to `.store`, and then an invariant of the manager might get broken? I don't know. Maybe we should synchronize the three atomic writes to make sure they can't get interrupted.

`.set_shards` is only ever called in one place, `Client::start_connection`, which takes `&mut self` on the `Client`, preventing concurrent calls. Regardless, we could synchronize the calls, however I'm not sure how we could go about that.

**Comment by tazz4843** [comment]
As with the tokio-tungstenite upgrade, failing test seems to be unrelated: https://github.com/dtolnay/proc-macro2/issues/398

**Comment by tazz4843** [comment]
Test bot has been online for three days straight now without any heartbeat failures (through network loss etc etc). I think this has finally solved the issue.

**Review by arqunis — APPROVED** [review]
