### PR TITLE
Fix the type of `token` and add field `kind` to `Webhook`

### LINKED ISSUE #1246: Webhook's token field is optional
The current [Webhook struct](https://docs.rs/serenity/0.10.2/serenity/model/webhook/struct.Webhook.html) does not account for different webhook types and webhook's `token` field being optional. [Discord's documentation on webhooks](https://discord.com/developers/docs/resources/webhook#webhook-object-webhook-structure) marks field `token` as optional and so, it does not get included with type 2 webhooks. Currently (with "0.10.2"), retrieving a type 2 webhook, for example, when fetching guild's webhook list, will fail with the following message:
```
Error while sending HTTP request.

Caused by:
    0: Error while sending HTTP request.
    1: error decoding response body: missing field `token` at line 1 column 8716
    2: missing field `token` at line 1 column 8716
```

### PR DESCRIPTION
**Pull request by arqunis**
## Description

This changes the type for `Webhook::token` to `Option<String>` and adds a new field to the struct called `kind` with the type `WebhookType`. This updates the structure to [conform to Discord's schema](https://discord.com/developers/docs/resources/webhook#webhook-object-webhook-structure) and to resolve https://github.com/serenity-rs/serenity/issues/1246.

## Type of Change

This is a multiclass change in the `model` module. It improves the correspondence with Discord's API for webhooks, and fixes an issue with the `token` definition, but has to break the library's APi to fix it. This targets `current` despite the breaking change, as otherwise webhooks are broken.

## How Has This Been Tested?

This has been tested by calling `Guild::webhooks` in a guild that had both an incoming webhook and a channel follower webhook. The result was a success, returning a list with the webhooks without errors.

### CODE REVIEW

File: src/model/webhook.rs [hunk 1]
```diff
@@ -132,9 +180,14 @@ impl Webhook {
     ///
     /// # Errors
     ///
-    /// May return an [`Error::Http`] if the content is illformed, or if the token is invalid.
-    /// May also return an [`Error::Json`] if there is an error in deserializing Discord's response.
+    /// Returns an [`Error::Model`] if the [`token`] is `None`.
+    ///
+    /// May also return an [`Error::Http`] if the content is illformed, or if the token is invalid.
```
Comment (Lakelezz) [inline src/model/webhook.rs]:
```suggestion
    /// May also return an [`Error::Http`] if the content is malformed, or if the token is invalid.
```
It's more common to say *malformed*.

File: src/model/webhook.rs [hunk 2]
```diff
@@ -132,9 +180,14 @@ impl Webhook {
...
+    ///
+    /// Or may return an [`Error::Json`] if there is an error in deserializing Discord's response.
```
Comment (Lakelezz) [inline src/model/webhook.rs]:
```suggestion
    /// Or may return an [`Error::Json`] if there is an error in deserialising Discord's response.
```

File: src/model/webhook.rs [hunk 3]
```diff
@@ -230,9 +285,14 @@ impl Webhook {
     ///
     /// # Errors
     ///
-    /// May return [`Error::Http`] if the content is illformed, or if the webhook's token is invalid.
-    /// Also, may return an [`Error::Json`] if there is an error deserializing Discord's response.
+    /// Returns an [`Error::Model`] if the [`token`] is `None`.
+    ///
+    /// May also return an [`Error::Http`] if the content is illformed, or if the webhook's token is invalid.
```
Comment (Lakelezz) [inline src/model/webhook.rs]:
```suggestion
    /// May also return an [`Error::Http`] if the content is malformed, or if the webhook's token is invalid.
```
As said, *malformed* is the common way to express this.

File: src/model/webhook.rs [hunk 4]
```diff
@@ -230,9 +285,14 @@ impl Webhook {
...
+    ///
+    /// Or may return an [`Error::Json`] if there is an error deserializing Discord's response.
```
Comment (Lakelezz) [inline src/model/webhook.rs]:
```suggestion
    /// Or may return an [`Error::Json`] if there is an error deserialising Discord's response.
```

File: src/model/webhook.rs [hunk 5]
```diff
@@ -273,15 +328,20 @@ impl Webhook {
...
     /// # Errors
     ///
-    /// Returns an [`Error::Http`] if the http client errors or if Discord returns an error.
+    /// Returns an [`Error::Model`] if the [`token`] is `None`.
+    ///
+    /// May also return an [`Error::Http`] if the http client errors or if Discord returns an error.
     /// Such as if the `Webhook` was deleted.
     ///
-    /// May also return an [`Error::Json`] if there is an error in deserializing the response.
+    /// Or may return an [`Error::Json`] if there is an error deserializing Discord's response.
```
Comment (Lakelezz) [inline src/model/webhook.rs]:
```suggestion
    /// Or may return an [`Error::Json`] if there is an error deserialising Discord's response.
```

**Review by Lakelezz — CHANGES_REQUESTED** [review]
Thanks for fixing this, I just raised some textual concerns. The American wording is not even authored by you, but while we are at it, I hope it's okay for you to change that :)

**Comment by arqunis** [comment]
Done, performed a replace operation with regex for illformed to malformed and deserialization to deserialisation.

**Review by Lakelezz — APPROVED** [review]
Perfect, thanks a lot for taking your time to fix this! :)
